modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="equipmentexpanded"
version="${file.jarVersion}"
displayName="Equipment Expanded"
authors="Styanatos, Noqqerz"
description='''
Adds extra equipment slots and related items.
'''

[[dependencies.equipmentexpanded]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"